services:
  thomas-bonsignore:
    container_name: thomas-bonsignore
    image: ghcr.io/thomasbsgr/thomas-bonsignore:latest
    restart: unless-stopped
    networks:
      - caddy

networks:
  caddy:
    external: true
